-- Migration: Add webhook_deliveries table
-- Created: 2026-01-30
-- Description: Store webhook delivery logs for analytics, retry management, and multi-channel delivery
--
-- NOTE: The webhook_deliveries table was already created in 001_initial_schema.sql
-- with a minimal schema (id, webhook_id, event, payload, success, etc.).
-- The full schema upgrade (status, delivery_channel, attempts, delivery_id, etc.)
-- is handled entirely by 005_update_webhook_deliveries_schema.sql via safe
-- ALTER TABLE ... ADD COLUMN IF NOT EXISTS statements.
--
-- This file is intentionally a no-op to preserve migration sequence numbering.
SELECT 1;
