// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: intelligence/v1/intelligence.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntelligenceService_RateLimit_FullMethodName    = "/intelligence.v1.IntelligenceService/RateLimit"
	IntelligenceService_Auth_FullMethodName         = "/intelligence.v1.IntelligenceService/Auth"
	IntelligenceService_RecordEvents_FullMethodName = "/intelligence.v1.IntelligenceService/RecordEvents"
	IntelligenceService_GetLogs_FullMethodName      = "/intelligence.v1.IntelligenceService/GetLogs"
	IntelligenceService_Check_FullMethodName        = "/intelligence.v1.IntelligenceService/Check"
)

// IntelligenceServiceClient is the client API for IntelligenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ─────────────────────────────────────────────────────────────────────────────
// IntelligenceService — the full surface area of the intelligence plane.
//
// Design notes:
//   - RateLimit and Auth are unary: 5 ms hard deadline enforced by caller.
//   - RecordEvents is a client-streaming RPC: the proxy batches RequestEvent
//     messages and flushes them in a background goroutine. The server returns
//     a single RecordAck when the stream closes.
//   - GetLogs is a server-streaming RPC: the server pages results as it scans.
//   - Check is a unary health probe (used by the admin /health endpoint).
//
// ─────────────────────────────────────────────────────────────────────────────
type IntelligenceServiceClient interface {
	// Synchronous rate-limit check — must complete within 5 ms.
	RateLimit(ctx context.Context, in *RateLimitRequest, opts ...grpc.CallOption) (*RateLimitResponse, error)
	// Synchronous auth check — must complete within 5 ms.
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// Client-streaming: proxy streams batches of request events.
	// The server acknowledges when the stream closes.
	RecordEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestEvent, RecordAck], error)
	// Server-streaming: server pages log entries back to caller.
	GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// Unary health check — used by admin API.
	Check(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type intelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelligenceServiceClient(cc grpc.ClientConnInterface) IntelligenceServiceClient {
	return &intelligenceServiceClient{cc}
}

func (c *intelligenceServiceClient) RateLimit(ctx context.Context, in *RateLimitRequest, opts ...grpc.CallOption) (*RateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateLimitResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_RateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_Auth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) RecordEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestEvent, RecordAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IntelligenceService_ServiceDesc.Streams[0], IntelligenceService_RecordEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestEvent, RecordAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntelligenceService_RecordEventsClient = grpc.ClientStreamingClient[RequestEvent, RecordAck]

func (c *intelligenceServiceClient) GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IntelligenceService_ServiceDesc.Streams[1], IntelligenceService_GetLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntelligenceService_GetLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *intelligenceServiceClient) Check(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, IntelligenceService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntelligenceServiceServer is the server API for IntelligenceService service.
// All implementations must embed UnimplementedIntelligenceServiceServer
// for forward compatibility.
//
// ─────────────────────────────────────────────────────────────────────────────
// IntelligenceService — the full surface area of the intelligence plane.
//
// Design notes:
//   - RateLimit and Auth are unary: 5 ms hard deadline enforced by caller.
//   - RecordEvents is a client-streaming RPC: the proxy batches RequestEvent
//     messages and flushes them in a background goroutine. The server returns
//     a single RecordAck when the stream closes.
//   - GetLogs is a server-streaming RPC: the server pages results as it scans.
//   - Check is a unary health probe (used by the admin /health endpoint).
//
// ─────────────────────────────────────────────────────────────────────────────
type IntelligenceServiceServer interface {
	// Synchronous rate-limit check — must complete within 5 ms.
	RateLimit(context.Context, *RateLimitRequest) (*RateLimitResponse, error)
	// Synchronous auth check — must complete within 5 ms.
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	// Client-streaming: proxy streams batches of request events.
	// The server acknowledges when the stream closes.
	RecordEvents(grpc.ClientStreamingServer[RequestEvent, RecordAck]) error
	// Server-streaming: server pages log entries back to caller.
	GetLogs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	// Unary health check — used by admin API.
	Check(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedIntelligenceServiceServer()
}

// UnimplementedIntelligenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntelligenceServiceServer struct{}

func (UnimplementedIntelligenceServiceServer) RateLimit(context.Context, *RateLimitRequest) (*RateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RateLimit not implemented")
}
func (UnimplementedIntelligenceServiceServer) Auth(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedIntelligenceServiceServer) RecordEvents(grpc.ClientStreamingServer[RequestEvent, RecordAck]) error {
	return status.Error(codes.Unimplemented, "method RecordEvents not implemented")
}
func (UnimplementedIntelligenceServiceServer) GetLogs(*LogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedIntelligenceServiceServer) Check(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedIntelligenceServiceServer) mustEmbedUnimplementedIntelligenceServiceServer() {}
func (UnimplementedIntelligenceServiceServer) testEmbeddedByValue()                             {}

// UnsafeIntelligenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntelligenceServiceServer will
// result in compilation errors.
type UnsafeIntelligenceServiceServer interface {
	mustEmbedUnimplementedIntelligenceServiceServer()
}

func RegisterIntelligenceServiceServer(s grpc.ServiceRegistrar, srv IntelligenceServiceServer) {
	// If the following call panics, it indicates UnimplementedIntelligenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntelligenceService_ServiceDesc, srv)
}

func _IntelligenceService_RateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).RateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_RateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).RateLimit(ctx, req.(*RateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_Auth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntelligenceService_RecordEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntelligenceServiceServer).RecordEvents(&grpc.GenericServerStream[RequestEvent, RecordAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntelligenceService_RecordEventsServer = grpc.ClientStreamingServer[RequestEvent, RecordAck]

func _IntelligenceService_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IntelligenceServiceServer).GetLogs(m, &grpc.GenericServerStream[LogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntelligenceService_GetLogsServer = grpc.ServerStreamingServer[LogEntry]

func _IntelligenceService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntelligenceServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntelligenceService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntelligenceServiceServer).Check(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IntelligenceService_ServiceDesc is the grpc.ServiceDesc for IntelligenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntelligenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "intelligence.v1.IntelligenceService",
	HandlerType: (*IntelligenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RateLimit",
			Handler:    _IntelligenceService_RateLimit_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _IntelligenceService_Auth_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _IntelligenceService_Check_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecordEvents",
			Handler:       _IntelligenceService_RecordEvents_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetLogs",
			Handler:       _IntelligenceService_GetLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "intelligence/v1/intelligence.proto",
}
