// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: intelligence/v1/intelligence.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse_Status int32

const (
	HealthResponse_UNKNOWN     HealthResponse_Status = 0
	HealthResponse_SERVING     HealthResponse_Status = 1
	HealthResponse_NOT_SERVING HealthResponse_Status = 2
)

// Enum value maps for HealthResponse_Status.
var (
	HealthResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthResponse_Status) Enum() *HealthResponse_Status {
	p := new(HealthResponse_Status)
	*p = x
	return p
}

func (x HealthResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_intelligence_v1_intelligence_proto_enumTypes[0].Descriptor()
}

func (HealthResponse_Status) Type() protoreflect.EnumType {
	return &file_intelligence_v1_intelligence_proto_enumTypes[0]
}

func (x HealthResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResponse_Status.Descriptor instead.
func (HealthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{9, 0}
}

type RateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIp      string                 `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRequest) Reset() {
	*x = RateLimitRequest{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRequest) ProtoMessage() {}

func (x *RateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRequest.ProtoReflect.Descriptor instead.
func (*RateLimitRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RateLimitRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RateLimitRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RateLimitRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	RetryAfterMs  int32                  `protobuf:"varint,3,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitResponse) Reset() {
	*x = RateLimitResponse{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitResponse) ProtoMessage() {}

func (x *RateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitResponse.ProtoReflect.Descriptor instead.
func (*RateLimitResponse) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RateLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *RateLimitResponse) GetRetryAfterMs() int32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RouteId       string                 `protobuf:"bytes,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *AuthRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *AuthResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type RequestEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path            string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Status          int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	LatencyMs       int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ClientIp        string                 `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Upstream        string                 `protobuf:"bytes,7,opt,name=upstream,proto3" json:"upstream,omitempty"`
	RouteId         string                 `protobuf:"bytes,8,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	HaproxyFrontend string                 `protobuf:"bytes,9,opt,name=haproxy_frontend,json=haproxyFrontend,proto3" json:"haproxy_frontend,omitempty"`
	HaproxyBackend  string                 `protobuf:"bytes,10,opt,name=haproxy_backend,json=haproxyBackend,proto3" json:"haproxy_backend,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BytesOut        int64                  `protobuf:"varint,12,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestEvent) Reset() {
	*x = RequestEvent{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEvent) ProtoMessage() {}

func (x *RequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEvent.ProtoReflect.Descriptor instead.
func (*RequestEvent) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{4}
}

func (x *RequestEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RequestEvent) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RequestEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RequestEvent) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *RequestEvent) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RequestEvent) GetHaproxyFrontend() string {
	if x != nil {
		return x.HaproxyFrontend
	}
	return ""
}

func (x *RequestEvent) GetHaproxyBackend() string {
	if x != nil {
		return x.HaproxyBackend
	}
	return ""
}

func (x *RequestEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RequestEvent) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

type RecordAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// count is the number of events the server accepted in this batch.
	Count         int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAck) Reset() {
	*x = RecordAck{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAck) ProtoMessage() {}

func (x *RecordAck) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAck.ProtoReflect.Descriptor instead.
func (*RecordAck) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{5}
}

func (x *RecordAck) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // 0 → server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{6}
}

func (x *LogsRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *LogsRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LogsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *LogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=intelligence.v1.HealthResponse_Status" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_intelligence_v1_intelligence_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_intelligence_v1_intelligence_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() HealthResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthResponse_UNKNOWN
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

var File_intelligence_v1_intelligence_proto protoreflect.FileDescriptor

const file_intelligence_v1_intelligence_proto_rawDesc = "" +
	"\n" +
	"\"intelligence/v1/intelligence.proto\x12\x0fintelligence.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"v\n" +
	"\x10RateLimitRequest\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"q\n" +
	"\x11RateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12$\n" +
	"\x0eretry_after_ms\x18\x03 \x01(\x05R\fretryAfterMs\"[\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\tR\arouteId\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\">\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"\x8f\x03\n" +
	"\fRequestEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x12\x1b\n" +
	"\tclient_ip\x18\x06 \x01(\tR\bclientIp\x12\x1a\n" +
	"\bupstream\x18\a \x01(\tR\bupstream\x12\x19\n" +
	"\broute_id\x18\b \x01(\tR\arouteId\x12)\n" +
	"\x10haproxy_frontend\x18\t \x01(\tR\x0fhaproxyFrontend\x12'\n" +
	"\x0fhaproxy_backend\x18\n" +
	" \x01(\tR\x0ehaproxyBackend\x128\n" +
	"\ttimestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tbytes_out\x18\f \x01(\x03R\bbytesOut\"!\n" +
	"\tRecordAck\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x8d\x01\n" +
	"\vLogsRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x8d\x02\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12=\n" +
	"\x06fields\x18\x05 \x03(\v2%.intelligence.v1.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rHealthRequest\"\xbc\x01\n" +
	"\x0eHealthResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.intelligence.v1.HealthResponse.StatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x8b\x03\n" +
	"\x13IntelligenceService\x12R\n" +
	"\tRateLimit\x12!.intelligence.v1.RateLimitRequest\x1a\".intelligence.v1.RateLimitResponse\x12C\n" +
	"\x04Auth\x12\x1c.intelligence.v1.AuthRequest\x1a\x1d.intelligence.v1.AuthResponse\x12K\n" +
	"\fRecordEvents\x12\x1d.intelligence.v1.RequestEvent\x1a\x1a.intelligence.v1.RecordAck(\x01\x12D\n" +
	"\aGetLogs\x12\x1c.intelligence.v1.LogsRequest\x1a\x19.intelligence.v1.LogEntry0\x01\x12H\n" +
	"\x05Check\x12\x1e.intelligence.v1.HealthRequest\x1a\x1f.intelligence.v1.HealthResponseB9Z7github.com/flexgate/proxy/internal/intelligence/grpc/pbb\x06proto3"

var (
	file_intelligence_v1_intelligence_proto_rawDescOnce sync.Once
	file_intelligence_v1_intelligence_proto_rawDescData []byte
)

func file_intelligence_v1_intelligence_proto_rawDescGZIP() []byte {
	file_intelligence_v1_intelligence_proto_rawDescOnce.Do(func() {
		file_intelligence_v1_intelligence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_intelligence_v1_intelligence_proto_rawDesc), len(file_intelligence_v1_intelligence_proto_rawDesc)))
	})
	return file_intelligence_v1_intelligence_proto_rawDescData
}

var file_intelligence_v1_intelligence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_intelligence_v1_intelligence_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_intelligence_v1_intelligence_proto_goTypes = []any{
	(HealthResponse_Status)(0),    // 0: intelligence.v1.HealthResponse.Status
	(*RateLimitRequest)(nil),      // 1: intelligence.v1.RateLimitRequest
	(*RateLimitResponse)(nil),     // 2: intelligence.v1.RateLimitResponse
	(*AuthRequest)(nil),           // 3: intelligence.v1.AuthRequest
	(*AuthResponse)(nil),          // 4: intelligence.v1.AuthResponse
	(*RequestEvent)(nil),          // 5: intelligence.v1.RequestEvent
	(*RecordAck)(nil),             // 6: intelligence.v1.RecordAck
	(*LogsRequest)(nil),           // 7: intelligence.v1.LogsRequest
	(*LogEntry)(nil),              // 8: intelligence.v1.LogEntry
	(*HealthRequest)(nil),         // 9: intelligence.v1.HealthRequest
	(*HealthResponse)(nil),        // 10: intelligence.v1.HealthResponse
	nil,                           // 11: intelligence.v1.LogEntry.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_intelligence_v1_intelligence_proto_depIdxs = []int32{
	12, // 0: intelligence.v1.RequestEvent.timestamp:type_name -> google.protobuf.Timestamp
	12, // 1: intelligence.v1.LogsRequest.since:type_name -> google.protobuf.Timestamp
	12, // 2: intelligence.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	11, // 3: intelligence.v1.LogEntry.fields:type_name -> intelligence.v1.LogEntry.FieldsEntry
	0,  // 4: intelligence.v1.HealthResponse.status:type_name -> intelligence.v1.HealthResponse.Status
	1,  // 5: intelligence.v1.IntelligenceService.RateLimit:input_type -> intelligence.v1.RateLimitRequest
	3,  // 6: intelligence.v1.IntelligenceService.Auth:input_type -> intelligence.v1.AuthRequest
	5,  // 7: intelligence.v1.IntelligenceService.RecordEvents:input_type -> intelligence.v1.RequestEvent
	7,  // 8: intelligence.v1.IntelligenceService.GetLogs:input_type -> intelligence.v1.LogsRequest
	9,  // 9: intelligence.v1.IntelligenceService.Check:input_type -> intelligence.v1.HealthRequest
	2,  // 10: intelligence.v1.IntelligenceService.RateLimit:output_type -> intelligence.v1.RateLimitResponse
	4,  // 11: intelligence.v1.IntelligenceService.Auth:output_type -> intelligence.v1.AuthResponse
	6,  // 12: intelligence.v1.IntelligenceService.RecordEvents:output_type -> intelligence.v1.RecordAck
	8,  // 13: intelligence.v1.IntelligenceService.GetLogs:output_type -> intelligence.v1.LogEntry
	10, // 14: intelligence.v1.IntelligenceService.Check:output_type -> intelligence.v1.HealthResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_intelligence_v1_intelligence_proto_init() }
func file_intelligence_v1_intelligence_proto_init() {
	if File_intelligence_v1_intelligence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_intelligence_v1_intelligence_proto_rawDesc), len(file_intelligence_v1_intelligence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_intelligence_v1_intelligence_proto_goTypes,
		DependencyIndexes: file_intelligence_v1_intelligence_proto_depIdxs,
		EnumInfos:         file_intelligence_v1_intelligence_proto_enumTypes,
		MessageInfos:      file_intelligence_v1_intelligence_proto_msgTypes,
	}.Build()
	File_intelligence_v1_intelligence_proto = out.File
	file_intelligence_v1_intelligence_proto_goTypes = nil
	file_intelligence_v1_intelligence_proto_depIdxs = nil
}
