// Package grpc provides a gRPC implementation of the intelligence.Client
// interface. Generated protobuf code lives in the pb/ sub-package.
//
// Code generation:
//
//	make proto-gen
//
// Do NOT edit files under pb/ — they are generated by protoc.
package grpc
