/**
 * HAProxy Configuration Generator
 * Generates HAProxy config from database routes
 */

import fs from 'fs/promises';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import { logger } from '../logger';
import { RouteRepository } from '../database/repositories/routesRepository';

const execAsync = promisify(exec);

interface HAProxyBackend {
  name: string;
  servers: Array<{
    name: string;
    address: string;
    port: number;
    weight: number;
    maxconn: number;
  }>;
  healthCheck?: {
    uri: string;
    interval: string;
    rise: number;
    fall: number;
  };
  rateLimit?: {
    maxRequests: number;
    windowSeconds: number;
  };
  circuitBreaker?: {
    failureThreshold: number;
    timeout: number;
  };
}

export class HAProxyConfigGenerator {
  private configPath: string;
  private templatePath: string;
  private routeRepo: RouteRepository;

  constructor() {
    this.configPath = process.env.HAPROXY_CONFIG_PATH || '/etc/haproxy/haproxy.cfg';
    this.templatePath = path.join(__dirname, '../../haproxy/haproxy.cfg.template');
    this.routeRepo = new RouteRepository();
  }

  /**
   * Generate HAProxy configuration from database
   */
  async generateConfig(): Promise<string> {
    try {
      logger.info('Generating HAProxy configuration from database...');

      // Fetch all active routes from database
      const routes = await this.routeRepo.findAll({ enabled: true });

      // Convert routes to HAProxy backends
      const backends: HAProxyBackend[] = routes.map((route, index) => ({
        name: `backend_${route.name || `route_${index}`}`,
        servers: [{
          name: `server_${index}_1`,
          address: new URL(route.targetUrl).hostname,
          port: parseInt(new URL(route.targetUrl).port) || 80,
          weight: route.weight || 100,
          maxconn: route.maxConnections || 1000,
        }],
        healthCheck: route.healthCheck ? {
          uri: route.healthCheck.path || '/health',
          interval: `${route.healthCheck.interval || 5}s`,
          rise: route.healthCheck.rise || 2,
          fall: route.healthCheck.fall || 3,
        } : undefined,
        rateLimit: route.rateLimit ? {
          maxRequests: route.rateLimit.max,
          windowSeconds: Math.floor(route.rateLimit.windowMs / 1000),
        } : undefined,
        circuitBreaker: route.circuitBreaker ? {
          failureThreshold: route.circuitBreaker.failureThreshold,
          timeout: route.circuitBreaker.timeout,
        } : undefined,
      }));

      // Generate config from template
      const config = this.buildConfig(backends);

      logger.info(`Generated HAProxy config with ${backends.length} backends`);
      return config;

    } catch (error: any) {
      logger.error('Failed to generate HAProxy config', { error: error.message });
      throw error;
    }
  }

  /**
   * Build HAProxy configuration string
   */
  private buildConfig(backends: HAProxyBackend[]): string {
    let config = `# HAProxy Configuration - Auto-generated by FlexGate
# Generated at: ${new Date().toISOString()}

global
    maxconn 50000
    nbthread 4
    log stdout format raw local0 info
    stats socket /var/run/haproxy.sock mode 600 level admin expose-fd listeners
    stats timeout 2m

defaults
    mode http
    log global
    timeout connect 5s
    timeout client 30s
    timeout server 30s
    timeout http-request 10s
    option httplog
    option dontlognull
    option http-server-close
    option forwardfor except 127.0.0.0/8

frontend api_gateway
    bind *:8080
    
    # Global rate limiting stick table
    stick-table type ip size 100k expire 30s store http_req_rate(10s)
    http-request track-sc0 src
    http-request deny deny_status 429 if { sc_http_req_rate(0) gt 10000 }
    
    # Request ID
    unique-id-format %{+X}o\\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
    unique-id-header X-Request-ID
    
`;

    // Add ACLs and routing rules
    backends.forEach((backend, index) => {
      config += `    acl is_${backend.name} path_beg /route${index}\n`;
    });

    config += '\n';

    backends.forEach((backend) => {
      config += `    use_backend ${backend.name} if is_${backend.name}\n`;
    });

    config += '    default_backend backend_api\n\n';

    // Add backend definitions
    backends.forEach((backend) => {
      config += this.buildBackend(backend);
    });

    // Add stats page
    config += `
listen stats
    bind *:8404
    stats enable
    stats uri /stats
    stats refresh 5s
    stats auth admin:changeme
`;

    return config;
  }

  /**
   * Build backend configuration
   */
  private buildBackend(backend: HAProxyBackend): string {
    let config = `backend ${backend.name}\n`;
    config += `    balance roundrobin\n`;

    // Health check
    if (backend.healthCheck) {
      config += `    option httpchk GET ${backend.healthCheck.uri} HTTP/1.1\\r\\nHost:\\ localhost\n`;
      config += `    http-check expect status 200\n`;
    }

    // Servers
    backend.servers.forEach((server) => {
      let serverLine = `    server ${server.name} ${server.address}:${server.port}`;
      
      if (backend.healthCheck) {
        serverLine += ` check inter ${backend.healthCheck.interval}`;
        serverLine += ` rise ${backend.healthCheck.rise}`;
        serverLine += ` fall ${backend.healthCheck.fall}`;
      }
      
      serverLine += ` maxconn ${server.maxconn}`;
      serverLine += ` weight ${server.weight}`;
      
      config += serverLine + '\n';
    });

    // Circuit breaker (via retries)
    if (backend.circuitBreaker) {
      config += `    retry-on all-retryable-errors\n`;
      config += `    retries 3\n`;
      config += `    timeout server ${Math.floor(backend.circuitBreaker.timeout / 1000)}s\n`;
    }

    config += '\n';
    return config;
  }

  /**
   * Write configuration to file
   */
  async writeConfig(config: string): Promise<void> {
    try {
      await fs.writeFile(this.configPath, config, 'utf-8');
      logger.info(`HAProxy config written to ${this.configPath}`);
    } catch (error: any) {
      logger.error('Failed to write HAProxy config', { error: error.message });
      throw error;
    }
  }

  /**
   * Validate HAProxy configuration
   */
  async validateConfig(): Promise<boolean> {
    try {
      const { stdout, stderr } = await execAsync(`haproxy -c -f ${this.configPath}`);
      
      if (stderr && stderr.includes('error')) {
        logger.error('HAProxy config validation failed', { stderr });
        return false;
      }

      logger.info('HAProxy config validation passed');
      return true;
    } catch (error: any) {
      logger.error('HAProxy config validation error', { error: error.message });
      return false;
    }
  }

  /**
   * Reload HAProxy with new configuration
   */
  async reloadHAProxy(): Promise<void> {
    try {
      // First validate
      const isValid = await this.validateConfig();
      if (!isValid) {
        throw new Error('HAProxy configuration is invalid');
      }

      // Reload HAProxy (graceful reload)
      await execAsync('systemctl reload haproxy || podman kill -s HUP flexgate-haproxy');
      
      logger.info('HAProxy reloaded successfully');
    } catch (error: any) {
      logger.error('Failed to reload HAProxy', { error: error.message });
      throw error;
    }
  }

  /**
   * Full update: generate, validate, and reload
   */
  async update(): Promise<void> {
    const config = await this.generateConfig();
    await this.writeConfig(config);
    await this.reloadHAProxy();
  }
}

export default new HAProxyConfigGenerator();
